### ISSUE TITLE
render("error") renders nothing

### ISSUE THREAD

**Issue by Robin-Sch** [Androz2091/paypal-bot#4]
When someone pays, then get redirected to /check and to /payment/blabla, if they then visit /check again they trigger [https://github.com/Androz2091/paypal-bot/blob/master/server.js#L92](url) which gives failed to lookup error.

**Comment by Androz2091** [comment]
Yes, you're right, the error page doesn't exist. I will add it.

**Comment by Androz2091** [comment]
Closed by @HideakiAtsuyo's #5 PR.
